-- =========================================================
-- RoomHub / La SandBox de Draze
-- Base anime + personnages
-- =========================================================

create extension if not exists pgcrypto;


-- =========================================================
-- ANIME
-- =========================================================

create table if not exists public.anime (
  id bigint generated by default as identity primary key,

  -- Nom utilisé par TON application
  name text not null,

  -- Image principale de l'anime
  image_url text,

  -- Petite version de l'image
  image_small_url text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint anime_name_unique unique (name)
);


-- =========================================================
-- IDS MAL / TENRAI
-- =========================================================
--
-- Un anime de notre application peut correspondre
-- à plusieurs entrées MyAnimeList.
--
-- Exemple :
--
-- Shingeki no Kyojin
--   ├── 16498
--   ├── 25777
--   ├── 35760
--   └── 40028
--

create table if not exists public.anime_sources (
  id bigint generated by default as identity primary key,

  anime_id bigint not null
    references public.anime(id)
    on delete cascade,

  mal_id integer not null,

  created_at timestamptz not null default now(),

  constraint anime_sources_mal_id_unique
    unique (mal_id),

  constraint anime_sources_anime_mal_unique
    unique (anime_id, mal_id)
);


create index if not exists idx_anime_sources_anime_id
on public.anime_sources(anime_id);


-- =========================================================
-- PERSONNAGES
-- =========================================================

create table if not exists public.characters (
  id bigint generated by default as identity primary key,

  -- ID MAL du personnage
  mal_id integer not null unique,

  name text not null,

  image_url text,

  image_small_url text,

  -- Informations récupérées depuis Tenrai
  role text,

  mal_favorites integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create index if not exists idx_characters_name
on public.characters using gin (
  to_tsvector('simple', name)
);

create index if not exists idx_characters_favorites
on public.characters(mal_favorites desc);


-- =========================================================
-- RELATION ANIME <-> PERSONNAGES
-- =========================================================

create table if not exists public.anime_characters (
  anime_id bigint not null
    references public.anime(id)
    on delete cascade,

  character_id bigint not null
    references public.characters(id)
    on delete cascade,

  created_at timestamptz not null default now(),

  primary key (anime_id, character_id)
);


create index if not exists idx_anime_characters_character_id
on public.anime_characters(character_id);


-- =========================================================
-- UPDATED_AT
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists anime_set_updated_at
on public.anime;

create trigger anime_set_updated_at
before update on public.anime
for each row
execute function public.set_updated_at();


drop trigger if exists characters_set_updated_at
on public.characters;

create trigger characters_set_updated_at
before update on public.characters
for each row
execute function public.set_updated_at();


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.anime enable row level security;
alter table public.anime_sources enable row level security;
alter table public.characters enable row level security;
alter table public.anime_characters enable row level security;


drop policy if exists "public can read anime"
on public.anime;

create policy "public can read anime"
on public.anime
for select
to anon, authenticated
using (true);


drop policy if exists "public can read anime sources"
on public.anime_sources;

create policy "public can read anime sources"
on public.anime_sources
for select
to anon, authenticated
using (true);


drop policy if exists "public can read characters"
on public.characters;

create policy "public can read characters"
on public.characters
for select
to anon, authenticated
using (true);


drop policy if exists "public can read anime characters"
on public.anime_characters;

create policy "public can read anime characters"
on public.anime_characters
for select
to anon, authenticated
using (true);


-- =========================================================
-- VUE COMPLETE POUR LES JEUX
-- =========================================================

create or replace view public.character_catalog as
select
  c.id,
  c.mal_id,
  c.name,
  c.image_url,
  c.image_small_url,
  c.role,
  c.mal_favorites,

  a.id as anime_id,
  a.name as anime_name,
  a.image_url as anime_image_url,
  a.image_small_url as anime_image_small_url

from public.characters c

join public.anime_characters ac
  on ac.character_id = c.id

join public.anime a
  on a.id = ac.anime_id;

-- =========================================================
-- RANDOM ANIME
-- =========================================================

create or replace function public.get_random_anime()
returns setof public.anime
language sql
security definer
set search_path = public
as $$
  select *
  from public.anime
  order by random()
  limit 1;
$$;


-- =========================================================
-- RANDOM CHARACTER
-- =========================================================

create or replace function public.get_random_character()
returns setof public.characters
language sql
security definer
set search_path = public
as $$
  select *
  from public.characters
  order by random()
  limit 1;
$$;


-- =========================================================
-- RANDOM CHARACTERS
-- =========================================================

create or replace function public.get_random_characters(
  requested_count integer
)
returns setof public.characters
language sql
security definer
set search_path = public
as $$
  select *
  from public.characters
  order by random()
  limit greatest(requested_count, 0);
$$;