export const A_LA_SUITE_THEMES = [
  "Des animés qui commencent par la lettre A",
  "Des animés qui commencent par la lettre B",
  "Des animés qui commencent par la lettre C",
  "Des animés qui commencent par la lettre D",
  "Des animés qui commencent par la lettre E",
  "Des animés qui commencent par la lettre F",
  "Des animés qui commencent par la lettre G",
  "Des animés qui commencent par la lettre H",
  "Des animés qui commencent par la lettre I",
  "Des animés qui commencent par la lettre J",
  "Des animés qui commencent par la lettre K",
  "Des animés qui commencent par la lettre L",
  "Des animés qui commencent par la lettre M",
  "Des animés qui commencent par la lettre N",
  "Des animés qui commencent par la lettre O",
  "Des animés qui commencent par la lettre P",
  "Des animés qui commencent par la lettre Q",
  "Des animés qui commencent par la lettre R",
  "Des animés qui commencent par la lettre S",
  "Des animés qui commencent par la lettre T",
  "Des animés qui commencent par la lettre U",
  "Des animés qui commencent par la lettre V",
  "Des animés qui commencent par la lettre W",
  "Des animés qui commencent par la lettre X",
  "Des animés qui commencent par la lettre Y",
  "Des animés qui commencent par la lettre Z",
  "Des animés avec un héros qui possède des pouvoirs magiques ou surnaturels",
  "Des animés dont le personnage principal est un lycéen",
  "Des animés avec une équipe de protagonistes (à partir de 3 personnages)",
  "Des animés avec un couple/duo de protagonistes",
  "Des animés avec un tournoi",
  "Des animés avec des robots",
  "Des animés avec des vampires",
  "Des animés avec des démons",
  "Des animés avec des voyages dans le temps",
  "Des animés adaptés d'un manga",
  "Des animés avec un personnage principal féminin",
  "Des animés avec un héros qui utilise une épée",
] as const;
export type ALaSuiteTheme = typeof A_LA_SUITE_THEMES[number];
