create extension if not exists pgcrypto;

create table if not exists public.anime (
  id bigint generated by default as identity primary key,
  mal_id integer not null unique,
  name text not null,
  image_url text,
  image_small_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  mal_id integer not null unique,
  anime_id bigint not null references public.anime(id) on delete cascade,
  name text not null,
  image_url text,
  image_small_url text,
  role text,
  mal_favorites integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_anime_name on public.anime using gin (to_tsvector('simple', name));
create index if not exists idx_characters_name on public.characters using gin (to_tsvector('simple', name));
create index if not exists idx_characters_anime_id on public.characters(anime_id);
create index if not exists idx_characters_favorites on public.characters(mal_favorites desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists anime_set_updated_at on public.anime;
create trigger anime_set_updated_at before update on public.anime
for each row execute function public.set_updated_at();

drop trigger if exists characters_set_updated_at on public.characters;
create trigger characters_set_updated_at before update on public.characters
for each row execute function public.set_updated_at();

alter table public.anime enable row level security;
alter table public.characters enable row level security;

drop policy if exists "public can read anime" on public.anime;
create policy "public can read anime" on public.anime for select to anon, authenticated using (true);

drop policy if exists "public can read characters" on public.characters;
create policy "public can read characters" on public.characters for select to anon, authenticated using (true);

create or replace view public.character_catalog as
select c.id, c.mal_id, c.name, c.image_url, c.image_small_url, c.role,
       c.mal_favorites, a.id as anime_id, a.mal_id as anime_mal_id,
       a.name as anime_name, a.image_url as anime_image_url,
       a.image_small_url as anime_image_small_url
from public.characters c
join public.anime a on a.id = c.anime_id;
